console.log("Test package that does not belong on the internet really")
console.log("An inbetween commit")
console.log("Another commit")
console.log("This is for 1.0.1-canary.0")
console.log("This is for 1.0.1-canary.1")
console.log("This is for 1.0.1-canary.2")
console.log("This is for 1.0.1-canary.3")
console.log("This is for 1.0.1-canary.4")