name: Build & Test
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install ci

      - name: Boostrap
        run: npm run lerna bootstrap

      - name: Build 
        run: npm run build
        
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Publish (canary)
        if: startsWith(github.ref, 'refs/tags/v') && `contains(github.ref, 'canary') == true
        run: |
          yarn run lerna changed && yarn run lerna publish from-git --no-verify-access --dist-tag canary --canary --preid canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish (stable)
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'canary') == false
        run: |
          yarn run lerna changed && yarn run lerna publish from-git --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}