name: Build & Test
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    types: [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
    - name: Install dependencies
      run: yarn lerna bootstrap
    - name: Build 
      run: yarn lerna build
    - name: Cache build
      uses: actions/cache@v2
      env:
        cache-name: cache-build
      id: cache-build
      with:
        path: ./*
        key: ${{ github.sha }}