name: Build & Test
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install ci

      - name: Boostrap
        run: npm run lerna bootstrap

      - name: Build 
        run: npm run build
        
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          # pulls all commits and tags (needed for lerna / semantic release to correctly version)
          fetch-depth: 0

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
          registry-url: https://registry.npmjs.org/

      - name: Configure Git CI User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
      - name: Publish (canary)
        if: contains(github.ref, 'canary') == true
        run: |
          npm run lerna -- changed && npm run lerna -- publish from-git --no-verify-access --dist-tag canary --canary --preid canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish (stable)
        if: contains(github.ref, 'canary') == false
        run: |
          npm run lerna -- changed && npm run lerna -- publish from-git --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 