name: "Publish"

on:
  workflow_run:
    workflows: ["Build & Test"]
    types: [completed]
      
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          # pulls all commits and tags (needed for lerna / semantic release to correctly version)
          fetch-depth: 0

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
          registry-url: https://registry.npmjs.org/

      - name: Configure Git CI User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Publish (canary)
        if: contains(github.ref, 'canary') == true
        run: |
          yarn run lerna changed && yarn run lerna publish from-git --no-verify-access --dist-tag canary --canary --preid canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish (stable)
        if: contains(github.ref, 'canary') == false
        run: |
          yarn run lerna changed && yarn run lerna publish from-git --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}